# Mongodb
mongo_add = "localhost"

# Train data 
sample_size = "all" # "all" to use all the data

# Models
seed = 222 # Reprodutible seed
splits = 5 # K folds in the data
repeats = 5 # Number of cvs
threads = -1 # -1 to use all available cores